ant.mkdir(dir:"${basedir}/license-config")
ant.copy(file:"${pluginBasedir}/scripts/license-config/privateKeys.store", todir:"${basedir}/license-config")
ant.copy(file:"${pluginBasedir}/scripts/license-config/LicensePrivateConfig.properties", todir:"${basedir}/license-config")
ant.copy(file:"${pluginBasedir}/scripts/license-config/publicCerts.store", todir:"${basedir}/grails-app/conf")
ant.copy(file:"${pluginBasedir}/scripts/LicensePublicConfig.groovy", todir:"${basedir}/grails-app/conf")
ant.copy(file:"${pluginBasedir}/scripts/LicenseFilters.groovy", todir:"${basedir}/grails-app/conf")
